_prefs: 
  mapid: wmm2016.8a3ec4fa
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 17.2266
  - 28.6135
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: ''
source: "mapbox:///wmm2016.5dfb14b7"
styles: 
  - style.mss
template: ''
