_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 16.6113
  - -5.7034
  - 3
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 6
minzoom: 0
name: ''
source: "tmsource:///Users/andrewbollinger/github-repos/microinsurance-dashboard/labels.tm2source"
styles: 
  - style.mss
template: ''
