_prefs: 
  mapid: devseed.3255becb
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 1.8396
  - 5.2323
  - 0
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 6
minzoom: 0
name: ''
source: "mapbox:///devseed.33074b4e"
styles: 
  - style.mss
template: ''
